# -*- mode: ruby -*-
# vi: set ft=ruby :

def define_node(config, node_name, cpu, memory)
  config.vm.define node_name do |node|
    node.vm.box = "centos/7"
    node.vm.hostname = node_name
    node.vm.network :private_network, type: "dhcp"
    node.vm.network :forwarded_port, guest: 22, host: 2238

    node.vm.provider :virtualbox do |v|
      v.cpus = cpu
      v.memory = memory
      v.customize ['modifyvm', :id, '--natnet1', '192.168.28.0/24']
    end

    # FIXME the provisioner.sh file expects the file there ->
    node.vm.provision "file", source: "files/local.conf." + node_name,
                              destination: "/home/vagrant/local.conf"
    node.vm.provision "shell", path: "provisioner.sh"
    # FIXME <- the copy of the local.conf must be simpler
  end
end

Vagrant.configure(2) do |config|
  define_node(config, "aio", "4", "4096")
end
