# -*- mode: ruby -*-
# vi: set ft=ruby :

def define_node(config, node_name, ip_address, cpu, memory)
  config.vm.define node_name do |node|
    node.vm.box = "ubuntu/trusty64"
    node.vm.hostname = node_name
    node.vm.network :private_network, ip: ip_address

    node.vm.provider :virtualbox do |v|
      v.cpus = cpu
      v.memory = memory
    end

    # FIXME the provisioner.sh file expects the file there ->
    node.vm.provision "file", source: "files/local.conf." + node_name,
                              destination: "/home/vagrant/local.conf"
    node.vm.provision "shell", path: "provisioner.sh"
    # FIXME <- the copy of the local.conf must be simpler
  end
end

Vagrant.configure(2) do |config|
  define_node(config, "controller", "192.168.56.150", "4", "4096")
  define_node(config, "compute1", "192.168.56.151", "2", "2048")
  define_node(config, "compute2", "192.168.56.152", "2", "2048")
end
